version: '3.8'

services:
  # mongodb container
  mongodb:
    image: mongo:latest
    container_name: midterm-mongo
    ports:
      - 27017:27017
    volumes:
      - midterm_data:/data/db

  # nginx reverse proxy container
  nginx:
    image: nginx:latest
    container_name: midterm-nginx
    ports:
      - 80:80
    depends_on:
      - app1
      - app2
      - app3
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

  # server scaling containers
  app1:
    image: midterm-node-docker-app:latest
    container_name: midterm-app1
    ports:
      - 3000:3000
    depends_on:
      - mongodb
    env_file:
      - ./.env
  app2:
    image: midterm-node-docker-app:latest
    container_name: midterm-app2
    ports:
      - 3001:3000
    depends_on:
      - mongodb
    env_file:
      - ./.env
  app3:
    image: midterm-node-docker-app:latest
    container_name: midterm-app3
    ports:
      - 3002:3000
    depends_on:
      - mongodb
    env_file:
      - ./.env

volumes:
  midterm_data:
