version: "3.8"

services:
    # MongoDB container
    mongodb:
        image: mongo:latest
        ports:
            - "27017:27017"
        volumes:
            - midterm_data:/data/db
        networks:
            - midterm-network
        deploy:
            placement:
                constraints:
                    - node.role == manager  # Chạy trên node manager để ổn định dữ liệu

    # Redis container
    redis:
        image: redis:latest
        ports:
            - "6379:6379"
        volumes:
            - redis_data:/data
        networks:
            - midterm-network
        deploy:
            placement:
                constraints:
                    - node.role == manager

    # Nginx reverse proxy container
    nginx:
        image: nginx:latest
        ports:
            - "80:80"
        depends_on:
            - app
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
        networks:
            - midterm-network
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure

    # Application container (scaled up)
    app:
        image: midterm-node-docker-app:latest
        environment:
            - NODE_ENV=production
        depends_on:
            - mongodb
            - redis
        env_file:
            - ./.env
        networks:
            - midterm-network
        deploy:
            replicas: 3  # Scale service app lên 3 replicas
            update_config:
                parallelism: 1
                delay: 10s
            restart_policy:
                condition: on-failure

networks:
    midterm-network:
        driver: overlay

volumes:
    midterm_data:
    redis_data:
